# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCredentialsBroker < Formula
  desc "Before kubectl run execute any command provides credential to kubectl"
  homepage "https://github.com/takumakume/kubectl-credentials-broker"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.1/kubectl-credentials-broker_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "f4598c3fdc5dfed2f2135e2b09d9a47103cd692277c0d08f901d083fdb7633a0"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.1/kubectl-credentials-broker_0.0.1_Darwin_arm64.tar.gz"
    sha256 "3072b85e5cdbdc1a2c0faf2fee13cb93615662f690f24b78e771ebd4b0e14932"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.1/kubectl-credentials-broker_0.0.1_Linux_x86_64.tar.gz"
    sha256 "ca8e66588c52f4a951ec0c798047e8a07c91b179b4084ed11349752c6446979c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.1/kubectl-credentials-broker_0.0.1_Linux_arm64.tar.gz"
    sha256 "94d4037e068e8184bea59a2f79e2dfd95fc2c7aaf1a4c211abd9988f968c5c78"
  end

  def install
    bin.install "kubectl-credentials-broker"
  end
end
