# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCredentialsBroker < Formula
  desc "Before kubectl run execute any command provides credential to kubectl"
  homepage "https://github.com/takumakume/kubectl-credentials-broker"
  version "0.0.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.3/kubectl-credentials-broker_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "eb01cd53df292988e70c985b0ec2e0bdb6b38af007dfafccb3d3186cf37323ce"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.3/kubectl-credentials-broker_0.0.3_Darwin_arm64.tar.gz"
    sha256 "bb57dc427ad80e2be4efa7a3dbc027fe8e6bed4dde36b8de00b5b738db2941b2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.3/kubectl-credentials-broker_0.0.3_Linux_x86_64.tar.gz"
    sha256 "2d285c541ad7dc4dad6a8be324ada7f7c2190f729144612a9a0831adccef1003"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.3/kubectl-credentials-broker_0.0.3_Linux_arm64.tar.gz"
    sha256 "0e4da984decef0fe4fc1677b2bfa8bdf87fed718fba74df63b2221efaf47730d"
  end

  def install
    bin.install "kubectl-credentials_broker"
  end
end
