# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCredentialsBroker < Formula
  desc "Before kubectl run execute any command provides credential to kubectl"
  homepage "https://github.com/takumakume/kubectl-credentials_broker"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.1/kubectl-credentials-broker_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "dc617693c6c9a7c8b361cf7ac02bb5aaa3c933dba4ece9bda7f3e543770c40fd"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.1/kubectl-credentials-broker_0.0.1_Darwin_arm64.tar.gz"
    sha256 "995dcf4860052c43ac507e2b039e67927568b91b0d56fa865db4dc195efb368a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.1/kubectl-credentials-broker_0.0.1_Linux_x86_64.tar.gz"
    sha256 "cc5d5d06904700ec6330fa5e5a0f30ab1151d0f75c9e8dca3ffa3d784a6da48f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.1/kubectl-credentials-broker_0.0.1_Linux_arm64.tar.gz"
    sha256 "af6c35baff20202efae1431c25d57d80f46b0fb3e206f5a0cc70ae913204e70b"
  end

  def install
    bin.install "kubectl-credentials_broker"
  end
end
