# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCredentialsBroker < Formula
  desc "Before kubectl run execute any command provides credential to kubectl"
  homepage "https://github.com/takumakume/kubectl-credentials_broker"
  version "0.0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.2/kubectl-credentials-broker_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "de09054c43c06ffe1f0574c896e935b4f13530ef2563d4e9f2314bd98a19297a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.2/kubectl-credentials-broker_0.0.2_Darwin_arm64.tar.gz"
    sha256 "a5d0ad0c959a66aa9ee3b3986fbe171e8c8944dc9c8d79e99a4bc8167e3c66a8"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.2/kubectl-credentials-broker_0.0.2_Linux_x86_64.tar.gz"
    sha256 "5065f721539c1c5bcba0bfc915869edc8b74c596299ee317f59c7d5b3c8c602b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/takumakume/kubectl-credentials-broker/releases/download/0.0.2/kubectl-credentials-broker_0.0.2_Linux_arm64.tar.gz"
    sha256 "80d3557ed11411f3e41cd140157e01c11cb1c6787e74f4747116b5ae7b34fef6"
  end

  def install
    bin.install "kubectl-credentials-broker"
  end
end
